do $$ begin create type core.iiu_score_direction as enum ('direct', 'inverse', 'checklist', 'manual'); exception when duplicate_object then null; end $$;

do $$ begin create type core.iiu_city_profile as enum ('pequeno', 'medio', 'grande', 'metropole'); exception when duplicate_object then null; end $$;

create table if not exists core.iiu_dimensions (code text primary key, name text not null unique, color text not null, display_order smallint not null unique check (display_order > 0), created_at timestamptz not null default now());

create table if not exists core.iiu_dimension_weights (city_profile core.iiu_city_profile not null, dimension_code text not null references core.iiu_dimensions(code) on delete restrict, weight numeric(5,2) not null check (weight > 0 and weight <= 100), primary key (city_profile, dimension_code));

alter table municipal.indicators add column if not exists iiu_dimension_code text references core.iiu_dimensions(code) on delete restrict, add column if not exists iiu_type text, add column if not exists source_description text, add column if not exists score_direction core.iiu_score_direction, add column if not exists checklist_max numeric, add column if not exists iiu_enabled boolean not null default false;

create table if not exists core.iiu_indicator_benchmarks (indicator_id uuid not null references municipal.indicators(id) on delete cascade, city_profile core.iiu_city_profile not null, minimum_value numeric not null, maximum_value numeric not null, updated_at timestamptz not null default now(), primary key (indicator_id, city_profile), check (minimum_value < maximum_value));

insert into core.iiu_dimensions (code, name, color, display_order) values ('mob', 'Mobilidade', '#3b82f6', 1) on conflict (code) do update set name = excluded.name, color = excluded.color, display_order = excluded.display_order;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('pequeno'::core.iiu_city_profile, 'mob', 10) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('medio'::core.iiu_city_profile, 'mob', 15) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('grande'::core.iiu_city_profile, 'mob', 18) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('metropole'::core.iiu_city_profile, 'mob', 20) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_do_transporte_publico', 'Cobertura do transporte público', 'Mobilidade', '% da população a menos de 500m de ponto de transporte', '% população', 'anual', '% da população a menos de 500m de ponto de transporte', 'mob', 'Acesso', 'GTFS / OpenStreetMap', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 18, 82 from municipal.indicators where code = 'cobertura_do_transporte_publico' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 18, 82 from municipal.indicators where code = 'cobertura_do_transporte_publico' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 18, 82 from municipal.indicators where code = 'cobertura_do_transporte_publico' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 18, 82 from municipal.indicators where code = 'cobertura_do_transporte_publico' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('pontualidade_do_transporte_publico', 'Pontualidade do transporte público', 'Mobilidade', 'Viagens no horário ÷ total de viagens × 100', '% viagens no horário', 'anual', 'Viagens no horário ÷ total de viagens × 100', 'mob', 'Eficiência', 'Google Maps API / Moovit', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('infraestrutura_cicloviaria', 'Infraestrutura cicloviária', 'Mobilidade', 'Extensão total de ciclovias e ciclofaixas ÷ pop. × 100.000', 'km/100k hab.', 'anual', 'Extensão total de ciclovias e ciclofaixas ÷ pop. × 100.000', 'mob', 'Sustentabilidade', 'OpenStreetMap + campo', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('acessibilidade_universal', 'Acessibilidade universal', 'Mobilidade', 'Veículos acessíveis PCD ÷ total da frota × 100', '% frota adaptada', 'anual', 'Veículos acessíveis PCD ÷ total da frota × 100', 'mob', 'Inclusão', 'ANTT / RNVL', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('tempo_medio_de_deslocamento', 'Tempo médio de deslocamento', 'Mobilidade', 'Tempo médio diário casa→trabalho (ida e volta)', 'min/dia', 'anual', 'Tempo médio diário casa→trabalho (ida e volta)', 'mob', 'Qualidade de vida', 'IBGE Censo / PNAD', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 20, 95 from municipal.indicators where code = 'tempo_medio_de_deslocamento' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 20, 95 from municipal.indicators where code = 'tempo_medio_de_deslocamento' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 20, 95 from municipal.indicators where code = 'tempo_medio_de_deslocamento' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 20, 95 from municipal.indicators where code = 'tempo_medio_de_deslocamento' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('digitalizacao_do_transporte', 'Digitalização do transporte', 'Mobilidade', 'Presença de: app, pagamento digital, GPS público, bilhete único', 'índice 0–4', 'anual', 'Presença de: app, pagamento digital, GPS público, bilhete único', 'mob', 'Inovação', 'Checklist presencial', 'checklist'::core.iiu_score_direction, 4, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_dimensions (code, name, color, display_order) values ('ene', 'Energia', '#0d9488', 2) on conflict (code) do update set name = excluded.name, color = excluded.color, display_order = excluded.display_order;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('pequeno'::core.iiu_city_profile, 'ene', 18) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('medio'::core.iiu_city_profile, 'ene', 15) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('grande'::core.iiu_city_profile, 'ene', 13) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('metropole'::core.iiu_city_profile, 'ene', 12) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('participacao_de_energias_renovaveis', 'Participação de energias renováveis', 'Energia', 'Consumo renovável ÷ consumo total × 100', '% da matriz local', 'anual', 'Consumo renovável ÷ consumo total × 100', 'ene', 'Geração limpa', 'ANEEL SIGEL / BIG', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 12, 88 from municipal.indicators where code = 'participacao_de_energias_renovaveis' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 12, 88 from municipal.indicators where code = 'participacao_de_energias_renovaveis' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 12, 88 from municipal.indicators where code = 'participacao_de_energias_renovaveis' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 12, 88 from municipal.indicators where code = 'participacao_de_energias_renovaveis' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('eficiencia_da_iluminacao_publica', 'Eficiência da iluminação pública', 'Energia', 'Pontos LED com telegestão ÷ total de pontos × 100', '% pontos LED', 'anual', 'Pontos LED com telegestão ÷ total de pontos × 100', 'ene', 'Eficiência', 'ANEEL SIGA / COSIP', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_de_coleta_seletiva', 'Cobertura de coleta seletiva', 'Energia', 'Domicílios com coleta seletiva ÷ total × 100', '% da população', 'anual', 'Domicílios com coleta seletiva ÷ total × 100', 'ene', 'Resíduos', 'SNIS Resíduos Sólidos', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('emissao_de_co2_per_capita', 'Emissão de CO₂ per capita', 'Energia', 'Total de emissões GEE municipais ÷ população', 'tCO₂/hab./ano', 'anual', 'Total de emissões GEE municipais ÷ população', 'ene', 'Clima', 'SEEG / Climate TRACE', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 1.2, 8.5 from municipal.indicators where code = 'emissao_de_co2_per_capita' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 1.2, 8.5 from municipal.indicators where code = 'emissao_de_co2_per_capita' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 1.2, 8.5 from municipal.indicators where code = 'emissao_de_co2_per_capita' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 1.2, 8.5 from municipal.indicators where code = 'emissao_de_co2_per_capita' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_vegetal_urbana', 'Cobertura vegetal urbana', 'Energia', 'Área verde total (parques, praças, APP) ÷ população', 'm²/hab.', 'anual', 'Área verde total (parques, praças, APP) ÷ população', 'ene', 'Ambiente', 'MapBiomas / INPE', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('indice_de_perdas_hidricas', 'Índice de perdas hídricas', 'Energia', 'Volume perdido na distribuição ÷ volume total produzido × 100', '% do volume', 'anual', 'Volume perdido na distribuição ÷ volume total produzido × 100', 'ene', 'Água', 'SNIS Água', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 18, 62 from municipal.indicators where code = 'indice_de_perdas_hidricas' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 18, 62 from municipal.indicators where code = 'indice_de_perdas_hidricas' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 18, 62 from municipal.indicators where code = 'indice_de_perdas_hidricas' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 18, 62 from municipal.indicators where code = 'indice_de_perdas_hidricas' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_dimensions (code, name, color, display_order) values ('sau', 'Saúde', '#f97316', 3) on conflict (code) do update set name = excluded.name, color = excluded.color, display_order = excluded.display_order;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('pequeno'::core.iiu_city_profile, 'sau', 20) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('medio'::core.iiu_city_profile, 'sau', 18) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('grande'::core.iiu_city_profile, 'sau', 16) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('metropole'::core.iiu_city_profile, 'sau', 14) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_da_atencao_basica_esf', 'Cobertura da atenção básica (ESF)', 'Saúde', 'Pop. coberta por equipes ESF ÷ pop. total × 100', '% da população', 'anual', 'Pop. coberta por equipes ESF ÷ pop. total × 100', 'sau', 'Acesso', 'e-Gestor AB / DAB-MS', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 35, 100 from municipal.indicators where code = 'cobertura_da_atencao_basica_esf' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 35, 100 from municipal.indicators where code = 'cobertura_da_atencao_basica_esf' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 35, 100 from municipal.indicators where code = 'cobertura_da_atencao_basica_esf' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 35, 100 from municipal.indicators where code = 'cobertura_da_atencao_basica_esf' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('leitos_hospitalares_por_habitante', 'Leitos hospitalares por habitante', 'Saúde', 'Total de leitos SUS e privados ÷ pop. × 1.000', 'leitos/1.000 hab.', 'anual', 'Total de leitos SUS e privados ÷ pop. × 1.000', 'sau', 'Capacidade', 'CNES / DATASUS', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('taxa_de_mortalidade_infantil', 'Taxa de mortalidade infantil', 'Saúde', 'Óbitos menores de 1 ano ÷ nascidos vivos × 1.000', 'por 1.000 NV', 'anual', 'Óbitos menores de 1 ano ÷ nascidos vivos × 1.000', 'sau', 'Resultado', 'SINASC + SIM / DATASUS', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 6, 28 from municipal.indicators where code = 'taxa_de_mortalidade_infantil' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 6, 28 from municipal.indicators where code = 'taxa_de_mortalidade_infantil' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 6, 28 from municipal.indicators where code = 'taxa_de_mortalidade_infantil' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 6, 28 from municipal.indicators where code = 'taxa_de_mortalidade_infantil' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('digitalizacao_dos_servicos_de_saude', 'Digitalização dos serviços de saúde', 'Saúde', 'Presença de: prontuário eletrônico, telemedicina, agendamento online, RNDS', 'índice 0–4', 'anual', 'Presença de: prontuário eletrônico, telemedicina, agendamento online, RNDS', 'sau', 'Tecnologia', 'Checklist RNDS / e-SUS', 'checklist'::core.iiu_score_direction, 4, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_vacinal', 'Cobertura vacinal', 'Saúde', 'Doses aplicadas no calendário ÷ público-alvo × 100', '% do público-alvo', 'anual', 'Doses aplicadas no calendário ÷ público-alvo × 100', 'sau', 'Prevenção', 'SI-PNI / DATASUS', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 55, 99 from municipal.indicators where code = 'cobertura_vacinal' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 55, 99 from municipal.indicators where code = 'cobertura_vacinal' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 55, 99 from municipal.indicators where code = 'cobertura_vacinal' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 55, 99 from municipal.indicators where code = 'cobertura_vacinal' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('caps_por_habitante', 'CAPS por habitante', 'Saúde', 'CAPS ativos ÷ pop. × 100.000', 'unid./100k hab.', 'anual', 'CAPS ativos ÷ pop. × 100.000', 'sau', 'Saúde mental', 'CNES / DATASUS', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_dimensions (code, name, color, display_order) values ('seg', 'Segurança', '#7c3aed', 4) on conflict (code) do update set name = excluded.name, color = excluded.color, display_order = excluded.display_order;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('pequeno'::core.iiu_city_profile, 'seg', 12) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('medio'::core.iiu_city_profile, 'seg', 13) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('grande'::core.iiu_city_profile, 'seg', 15) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('metropole'::core.iiu_city_profile, 'seg', 16) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('taxa_de_homicidios', 'Taxa de homicídios', 'Segurança', 'Homicídios dolosos ÷ pop. × 100.000', 'por 100k hab.', 'anual', 'Homicídios dolosos ÷ pop. × 100.000', 'seg', 'Violência letal', 'SSP estadual / FBSP', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 4, 68 from municipal.indicators where code = 'taxa_de_homicidios' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 4, 68 from municipal.indicators where code = 'taxa_de_homicidios' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 4, 68 from municipal.indicators where code = 'taxa_de_homicidios' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 4, 68 from municipal.indicators where code = 'taxa_de_homicidios' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('tempo_medio_de_resposta_a_ocorrencias', 'Tempo médio de resposta a ocorrências', 'Segurança', 'Tempo entre acionamento e chegada ao local (média mensal)', 'minutos', 'anual', 'Tempo entre acionamento e chegada ao local (média mensal)', 'seg', 'Resposta', 'PM / GCM / SAMU', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_de_videomonitoramento', 'Cobertura de videomonitoramento', 'Segurança', 'Câmeras de monitoramento ÷ área urbana em km²', 'câmeras/km²', 'anual', 'Câmeras de monitoramento ÷ área urbana em km²', 'seg', 'Tecnologia', 'Checklist presencial / PM', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('taxa_de_roubos_e_furtos', 'Taxa de roubos e furtos', 'Segurança', 'Registros de roubo + furto ÷ pop. × 100.000', 'por 100k hab.', 'anual', 'Registros de roubo + furto ÷ pop. × 100.000', 'seg', 'Patrimônio', 'SSP estadual', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 180, 2400 from municipal.indicators where code = 'taxa_de_roubos_e_furtos' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 180, 2400 from municipal.indicators where code = 'taxa_de_roubos_e_furtos' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 180, 2400 from municipal.indicators where code = 'taxa_de_roubos_e_furtos' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 180, 2400 from municipal.indicators where code = 'taxa_de_roubos_e_furtos' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('indice_de_policiamento_comunitario', 'Índice de policiamento comunitário', 'Segurança', 'Presença de: CONSEG ativo, base comunitária, patrulhamento a pé', 'índice 0–3', 'anual', 'Presença de: CONSEG ativo, base comunitária, patrulhamento a pé', 'seg', 'Prevenção', 'Checklist PM / GCM', 'checklist'::core.iiu_score_direction, 3, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('percepcao_de_seguranca', 'Percepção de segurança', 'Segurança', 'Nota média da população em survey sobre sensação de segurança', 'escala 0–10', 'anual', 'Nota média da população em survey sobre sensação de segurança', 'seg', 'Percepção', 'Survey próprio', 'checklist'::core.iiu_score_direction, 10, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_dimensions (code, name, color, display_order) values ('gov', 'Governança', '#d97706', 5) on conflict (code) do update set name = excluded.name, color = excluded.color, display_order = excluded.display_order;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('pequeno'::core.iiu_city_profile, 'gov', 15) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('medio'::core.iiu_city_profile, 'gov', 14) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('grande'::core.iiu_city_profile, 'gov', 14) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('metropole'::core.iiu_city_profile, 'gov', 14) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('maturidade_do_portal_de_dados_abertos', 'Maturidade do portal de dados abertos', 'Governança', 'Avaliação: existência, atualização, formatos abertos, APIs, licença', 'nível 1–5', 'anual', 'Avaliação: existência, atualização, formatos abertos, APIs, licença', 'gov', 'Transparência', 'dados.gov.br / CGU INDA', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('iegm_indice_de_efetividade_da_gestao', 'IEGM — Índice de Efetividade da Gestão', 'Governança', 'Nota oficial do TCE (i-Cidade, i-Saúde, i-Educ, i-Fiscal)', 'A a E', 'anual', 'Nota oficial do TCE (i-Cidade, i-Saúde, i-Educ, i-Fiscal)', 'gov', 'Gestão', 'TCE estadual / IRB', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('participacao_cidada_digital', 'Participação cidadã digital', 'Governança', 'Presença de: ouvidoria online, app municipal, OP digital, consultas públicas', 'índice 0–4', 'anual', 'Presença de: ouvidoria online, app municipal, OP digital, consultas públicas', 'gov', 'Participação', 'Checklist apps / ouvidoria', 'checklist'::core.iiu_score_direction, 4, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('digitalizacao_dos_servicos_publicos', 'Digitalização dos serviços públicos', 'Governança', 'Serviços realizáveis online ÷ total de serviços × 100', '% serviços online', 'anual', 'Serviços realizáveis online ÷ total de serviços × 100', 'gov', 'e-Gov', 'Portal gov.br / site municipal', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 5, 78 from municipal.indicators where code = 'digitalizacao_dos_servicos_publicos' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 5, 78 from municipal.indicators where code = 'digitalizacao_dos_servicos_publicos' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 5, 78 from municipal.indicators where code = 'digitalizacao_dos_servicos_publicos' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 5, 78 from municipal.indicators where code = 'digitalizacao_dos_servicos_publicos' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cumprimento_da_lai', 'Cumprimento da LAI', 'Governança', 'Nota do ranking nacional de transparência ativa (CGU)', 'pontuação 0–10', 'anual', 'Nota do ranking nacional de transparência ativa (CGU)', 'gov', 'Transparência', 'CGU Ranking Transparência Ativa', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 2, 9.5 from municipal.indicators where code = 'cumprimento_da_lai' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 2, 9.5 from municipal.indicators where code = 'cumprimento_da_lai' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 2, 9.5 from municipal.indicators where code = 'cumprimento_da_lai' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 2, 9.5 from municipal.indicators where code = 'cumprimento_da_lai' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('maturidade_em_ciberseguranca', 'Maturidade em cibersegurança', 'Governança', 'LGPD implementada, backup, CSIRT, política de segurança, DPO nomeado', 'nível 1–4', 'anual', 'LGPD implementada, backup, CSIRT, política de segurança, DPO nomeado', 'gov', 'Segurança digital', 'Checklist LGPD / TI', 'checklist'::core.iiu_score_direction, 5, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_dimensions (code, name, color, display_order) values ('eco', 'Economia', '#059669', 6) on conflict (code) do update set name = excluded.name, color = excluded.color, display_order = excluded.display_order;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('pequeno'::core.iiu_city_profile, 'eco', 10) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('medio'::core.iiu_city_profile, 'eco', 12) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('grande'::core.iiu_city_profile, 'eco', 14) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('metropole'::core.iiu_city_profile, 'eco', 15) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('pib_per_capita_municipal', 'PIB per capita municipal', 'Economia', 'PIB municipal ÷ população', 'R$/hab./ano', 'anual', 'PIB municipal ÷ população', 'eco', 'Riqueza', 'IBGE PIB Municípios / SIDRA', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 8500, 72000 from municipal.indicators where code = 'pib_per_capita_municipal' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 8500, 72000 from municipal.indicators where code = 'pib_per_capita_municipal' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 8500, 72000 from municipal.indicators where code = 'pib_per_capita_municipal' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 8500, 72000 from municipal.indicators where code = 'pib_per_capita_municipal' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('taxa_de_formalizacao_do_emprego', 'Taxa de formalização do emprego', 'Economia', 'Empregos formais (RAIS) ÷ pop. ocupada × 100', '% trabalhadores formais', 'anual', 'Empregos formais (RAIS) ÷ pop. ocupada × 100', 'eco', 'Trabalho', 'RAIS / CAGED / MTE', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 28, 82 from municipal.indicators where code = 'taxa_de_formalizacao_do_emprego' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 28, 82 from municipal.indicators where code = 'taxa_de_formalizacao_do_emprego' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 28, 82 from municipal.indicators where code = 'taxa_de_formalizacao_do_emprego' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 28, 82 from municipal.indicators where code = 'taxa_de_formalizacao_do_emprego' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('densidade_de_startups_e_inovacao', 'Densidade de startups e inovação', 'Economia', 'Startups ativas + incubadoras + parques tecnológicos ÷ pop. × 100k', 'startups/100k hab.', 'anual', 'Startups ativas + incubadoras + parques tecnológicos ÷ pop. × 100k', 'eco', 'Inovação', 'Abstartups / mapeamento manual', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_de_banda_larga', 'Cobertura de banda larga', 'Economia', 'Domicílios com banda larga fixa ÷ total × 100', '% domicílios', 'anual', 'Domicílios com banda larga fixa ÷ total × 100', 'eco', 'Conectividade', 'ANATEL / CGI.br', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 22, 91 from municipal.indicators where code = 'cobertura_de_banda_larga' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 22, 91 from municipal.indicators where code = 'cobertura_de_banda_larga' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 22, 91 from municipal.indicators where code = 'cobertura_de_banda_larga' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 22, 91 from municipal.indicators where code = 'cobertura_de_banda_larga' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('facilidade_para_abertura_de_empresas', 'Facilidade para abertura de empresas', 'Economia', 'Tempo médio para abertura de CNPJ no município (em dias)', 'dias', 'anual', 'Tempo médio para abertura de CNPJ no município (em dias)', 'eco', 'Ambiente de negócios', 'REDESIM / Junta Comercial', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('investimento_publico_em_inovacao', 'Investimento público em inovação', 'Economia', 'Orçamento C&T e inovação ÷ orçamento total × 100', '% do orçamento', 'anual', 'Orçamento C&T e inovação ÷ orçamento total × 100', 'eco', 'P&D', 'FINBRA / Portal Transparência', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_dimensions (code, name, color, display_order) values ('hab', 'Habitação', '#be185d', 7) on conflict (code) do update set name = excluded.name, color = excluded.color, display_order = excluded.display_order;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('pequeno'::core.iiu_city_profile, 'hab', 15) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('medio'::core.iiu_city_profile, 'hab', 13) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('grande'::core.iiu_city_profile, 'hab', 10) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into core.iiu_dimension_weights (city_profile, dimension_code, weight) values ('metropole'::core.iiu_city_profile, 'hab', 9) on conflict (city_profile, dimension_code) do update set weight = excluded.weight;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('deficit_habitacional', 'Déficit habitacional', 'Habitação', 'Déficit total ÷ total de domicílios × 100', '% dos domicílios', 'anual', 'Déficit total ÷ total de domicílios × 100', 'hab', 'Moradia', 'FJP / IBGE Censo', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 2, 22 from municipal.indicators where code = 'deficit_habitacional' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 2, 22 from municipal.indicators where code = 'deficit_habitacional' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 2, 22 from municipal.indicators where code = 'deficit_habitacional' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 2, 22 from municipal.indicators where code = 'deficit_habitacional' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_de_agua_tratada', 'Cobertura de água tratada', 'Habitação', 'Pop. atendida com água tratada ÷ pop. total × 100', '% da população', 'anual', 'Pop. atendida com água tratada ÷ pop. total × 100', 'hab', 'Saneamento', 'SNIS Água / IBGE', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 55, 100 from municipal.indicators where code = 'cobertura_de_agua_tratada' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 55, 100 from municipal.indicators where code = 'cobertura_de_agua_tratada' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 55, 100 from municipal.indicators where code = 'cobertura_de_agua_tratada' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 55, 100 from municipal.indicators where code = 'cobertura_de_agua_tratada' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('cobertura_de_esgoto_sanitario', 'Cobertura de esgoto sanitário', 'Habitação', 'Pop. com coleta e tratamento de esgoto ÷ total × 100', '% da população', 'anual', 'Pop. com coleta e tratamento de esgoto ÷ total × 100', 'hab', 'Saneamento', 'SNIS Esgoto', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 22, 91 from municipal.indicators where code = 'cobertura_de_esgoto_sanitario' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 22, 91 from municipal.indicators where code = 'cobertura_de_esgoto_sanitario' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 22, 91 from municipal.indicators where code = 'cobertura_de_esgoto_sanitario' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 22, 91 from municipal.indicators where code = 'cobertura_de_esgoto_sanitario' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('populacao_em_area_de_risco', 'População em área de risco', 'Habitação', 'Habitantes em áreas de risco geológico/hídrico ÷ pop. × 100', '% da população', 'anual', 'Habitantes em áreas de risco geológico/hídrico ÷ pop. × 100', 'hab', 'Risco', 'CEMADEN / IBGE', 'inverse'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'pequeno'::core.iiu_city_profile, 0.5, 18 from municipal.indicators where code = 'populacao_em_area_de_risco' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'medio'::core.iiu_city_profile, 0.5, 18 from municipal.indicators where code = 'populacao_em_area_de_risco' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'grande'::core.iiu_city_profile, 0.5, 18 from municipal.indicators where code = 'populacao_em_area_de_risco' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into core.iiu_indicator_benchmarks (indicator_id, city_profile, minimum_value, maximum_value) select id, 'metropole'::core.iiu_city_profile, 0.5, 18 from municipal.indicators where code = 'populacao_em_area_de_risco' on conflict (indicator_id, city_profile) do update set minimum_value = excluded.minimum_value, maximum_value = excluded.maximum_value, updated_at = now();

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('indice_de_pavimentacao_viaria', 'Índice de pavimentação viária', 'Habitação', 'Vias pavimentadas ÷ extensão total de vias × 100', '% das vias', 'anual', 'Vias pavimentadas ÷ extensão total de vias × 100', 'hab', 'Infraestrutura', 'e-SIC LAI / DNIT', 'direct'::core.iiu_score_direction, null, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

insert into municipal.indicators (code, name, dimension, definition, unit, expected_frequency, formula, iiu_dimension_code, iiu_type, source_description, score_direction, checklist_max, iiu_enabled, active) values ('maturidade_do_geoprocessamento', 'Maturidade do geoprocessamento', 'Habitação', 'Cadastro técnico, GIS municipal, PGV digital, BIM em obras', 'nível 1–4', 'anual', 'Cadastro técnico, GIS municipal, PGV digital, BIM em obras', 'hab', 'Tecnologia', 'Checklist GIS / cadastro', 'checklist'::core.iiu_score_direction, 4, true, true) on conflict (code) do update set name = excluded.name, dimension = excluded.dimension, definition = excluded.definition, unit = excluded.unit, expected_frequency = excluded.expected_frequency, formula = excluded.formula, iiu_dimension_code = excluded.iiu_dimension_code, iiu_type = excluded.iiu_type, source_description = excluded.source_description, score_direction = excluded.score_direction, checklist_max = excluded.checklist_max, iiu_enabled = true, active = true;

create or replace view public.iiu_indicator_catalog as select indicators.id, indicators.code, indicators.name, indicators.dimension, indicators.definition, indicators.unit, indicators.expected_frequency, indicators.formula, indicators.iiu_dimension_code, indicators.iiu_type, indicators.source_description, indicators.score_direction, indicators.checklist_max, dimensions.color, dimensions.display_order from municipal.indicators indicators join core.iiu_dimensions dimensions on dimensions.code = indicators.iiu_dimension_code where indicators.iiu_enabled and indicators.active;

create or replace view public.iiu_dimension_catalog as select dimensions.code, dimensions.name, dimensions.color, dimensions.display_order, weights.city_profile, weights.weight from core.iiu_dimensions dimensions join core.iiu_dimension_weights weights on weights.dimension_code = dimensions.code;

create or replace view public.iiu_indicator_benchmark_catalog as select indicators.code as indicator_code, benchmarks.city_profile, benchmarks.minimum_value, benchmarks.maximum_value from core.iiu_indicator_benchmarks benchmarks join municipal.indicators indicators on indicators.id = benchmarks.indicator_id;

grant select on public.iiu_indicator_catalog, public.iiu_dimension_catalog, public.iiu_indicator_benchmark_catalog to service_role;

create or replace view public.iiu_municipalities as select ibge_code, name, state from municipal.municipalities;
grant select on public.iiu_municipalities to service_role;
